name: on_push_main

on:
  push:
    branches: [main]
jobs:
  build:
    name: preview-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }} and Cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: './yarn.lock'

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }} 

      - name: Install Dependencies
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install
        
      - name: Run ESLint 
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: lint

      - name: Run tests
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: ci-test
          
      - name: Build on EAS
        run: eas build --profile preview --platform android --non-interactive --no-wait
